"""Pure offline asset preparation primitives for AGT Navigation V2.5."""

from .contracts import (
    AssetContractError,
    DatasetBinding,
    DerivationRecipe,
    RoutePolicy,
    sha256_file,
    sha256_path_bundle,
)
from .workspace import (
    MapWorkspace,
    compute_map_content_sha256,
    create_map_workspace,
    refresh_map_manifest,
)
from .map_validation import MapComplianceResult, validate_map_workspace
from .session_ingest import MappingSessionIngestResult, ingest_mapping_session
from .route_asset import (
    RouteSample,
    create_route_candidate_asset,
    derive_route_candidate,
    load_route_csv,
    write_route_csv,
)
from .feasibility import FeasibilityResult, validate_route_asset
from .alignment import AlignmentResult, identity_alignment, solve_site_control_points, write_alignment_report
from .preview import write_route_preview
from .tuning import apply_route_tuning
from .cleaning import append_cleaning_operation
from .site_package import (
    SitePackageComplianceResult,
    compute_site_package_content_sha256,
    create_site_package,
    generate_site_package_id,
    refresh_site_package,
    validate_site_package,
)
from .pcd_io import PcdCloud, PcdSchema, read_pcd, write_pcd
from .pointcloud_profile import DEFAULT_PERCENTILES, summarize_pointcloud
from .pointcloud_processing import (
    PointCloudProcessingCompliance,
    PointCloudProcessingResult,
    load_pointcloud_recipe,
    process_pointcloud,
    validate_pointcloud_processing,
)
from .navigation_map_derivation import (
    FREE,
    OCCUPIED,
    UNKNOWN,
    NAVIGATION_DERIVATION_SCHEMA,
    GroundRelativeNavigationConfig,
    NavigationMapResult,
    apply_navigation_overrides,
    derive_ground_relative_navigation_map,
    write_navigation_map_derivation,
)
from .navigation_grid import NavigationGridEvidence, load_navigation_grid
from .navigation_structure import (
    NavigationStructureConfig,
    NavigationStructureResult,
    RowModel,
    derive_navigation_structure,
)
from .navigation_corridor import (
    AislePairDiagnostic,
    CorridorRefinementConfig,
    CorridorRefinementResult,
    derive_corridor_refinement,
)
from .vehicle_corridor import (
    VehicleCorridorConfig,
    VehicleCorridorResult,
    derive_vehicle_corridor,
)
from .agricultural_aisle_graph import (
    AISLE_GRAPH_SCHEMA,
    AisleGraphConfig,
    AislePrimitive,
    AgriculturalAisleGraph,
    aisle_graph_to_dict,
    derive_agricultural_aisle_graph,
    write_agricultural_aisle_graph,
)
from .turn_zones import (
    TURN_ZONE_SCHEMA,
    TurnZone,
    TurnZoneConfig,
    TurnZoneSet,
    derive_turn_zone_candidates,
    turn_zones_to_dict,
    write_turn_zones,
)
from .vehicle_profile import (
    CanonicalVehicleProfile,
    load_canonical_vehicle_profile,
    vehicle_profile_to_route_binding,
)
from .agricultural_coverage_ordering import (
    COVERAGE_ORDER_SCHEMA,
    AisleRejection,
    AisleTraversal,
    AgriculturalCoverageOrder,
    ConnectorRequest,
    CoverageOrderingConfig,
    coverage_order_to_dict,
    derive_agricultural_coverage_order,
)
from .forward_connector import (
    FORWARD_CONNECTOR_SCHEMA,
    ForwardConnectorConfig,
    ForwardConnectorPlan,
    ForwardConnectorResult,
    ForwardConnectorSample,
    derive_forward_connector_plan,
    forward_connector_plan_to_dict,
)
from .forward_connector_diagnostics import (
    FORWARD_CONNECTOR_ZONE_FIT_SCHEMA,
    ForwardConnectorZoneFitDiagnostic,
    ForwardConnectorZoneFitReport,
    diagnose_forward_connector_zone_fit,
    forward_connector_zone_fit_to_dict,
    write_forward_connector_zone_fit_report,
)
from .forward_connector_navigation_gate import (
    FORWARD_CONNECTOR_NAVIGATION_GATE_SCHEMA,
    ForwardConnectorNavigationGateConfig,
    ForwardConnectorNavigationPlan,
    ForwardConnectorNavigationResult,
    GridPathEvidence,
    derive_forward_connector_navigation_gate,
    forward_connector_navigation_gate_to_dict,
    write_forward_connector_navigation_gate,
)
from .forward_connector_candidate_audit import (
    FORWARD_CONNECTOR_CANDIDATE_AUDIT_SCHEMA,
    ForwardCandidateAuditItem,
    ForwardConnectorCandidateAuditConfig,
    ForwardConnectorCandidateAuditPlan,
    ForwardConnectorCandidateAuditResult,
    derive_forward_connector_candidate_audit,
    forward_connector_candidate_audit_to_dict,
    write_forward_connector_candidate_audit,
)
from .turn_zone_refinement import (
    TURN_ZONE_REFINEMENT_SCHEMA,
    TurnZoneExpansionEvidence,
    TurnZoneRefinementConfig,
    TurnZoneRefinementPlan,
    TurnZoneRefinementProposal,
    derive_turn_zone_refinement_proposal,
    turn_zone_refinement_to_dict,
    write_turn_zone_refinement_proposal,
)
from .reverse_fallback_admission import (
    REVERSE_FALLBACK_ADMISSION_SCHEMA,
    ReverseFallbackAdmissionConfig,
    ReverseFallbackAdmissionItem,
    ReverseFallbackAdmissionPlan,
    derive_reverse_fallback_admission,
    reverse_fallback_admission_to_dict,
    write_reverse_fallback_admission,
)
from .agricultural_route_io import (
    load_agricultural_aisle_graph,
    load_coverage_connector_requests,
    load_turn_zones,
    write_agricultural_coverage_order,
    write_forward_connector_plan,
)
from .route_diagnostic_io import (
    load_forward_connector_candidate_audit,
    load_forward_connector_zone_fit_report,
)
from .route_debug_dataset import (
    ASSET_INVALID,
    ASSET_LOADED,
    ASSET_MISSING,
    RouteDebugAisleRecord,
    RouteDebugAssetState,
    RouteDebugConnectorRecord,
    RouteDebugCoverageRejection,
    RouteDebugCoverageTraversal,
    RouteDebugDataset,
    RouteDebugForwardCandidateRecord,
    RouteDebugLaneDiagnosticRecord,
    RouteDebugMotionSample,
    RouteDebugNoGoRegion,
    RouteDebugOccupancySourceRecord,
    RouteDebugVehicleLaneRecord,
    load_route_debug_dataset,
)
from .route_debug_overlay import (
    ROUTE_DEBUG_OVERLAY_SCHEMA,
    RouteDebugOverlayConfig,
    build_route_debug_overlay,
    write_route_debug_overlay,
)
from .site_boundary import (
    SITE_BOUNDARY_SCHEMA,
    SITE_BOUNDARY_SEMANTICS,
    SiteBoundary,
    load_site_boundary,
    polygon_strictly_inside_site_boundary,
    rasterize_site_boundary,
    validate_site_boundary,
    write_site_boundary,
)
from .traversability import (
    TRAVERSABILITY_EVIDENCE_SCHEMA,
    TraversabilityConfig,
    TraversabilityEvidence,
    derive_traversability_evidence,
)

__all__ = [
    "AssetContractError",
    "DatasetBinding",
    "DerivationRecipe",
    "RoutePolicy",
    "sha256_file",
    "sha256_path_bundle",
    "MapWorkspace",
    "compute_map_content_sha256",
    "create_map_workspace",
    "refresh_map_manifest",
    "MapComplianceResult",
    "validate_map_workspace",
    "MappingSessionIngestResult",
    "ingest_mapping_session",
    "RouteSample",
    "create_route_candidate_asset",
    "derive_route_candidate",
    "load_route_csv",
    "write_route_csv",
    "FeasibilityResult",
    "validate_route_asset",
    "AlignmentResult",
    "identity_alignment",
    "solve_site_control_points",
    "write_alignment_report",
    "write_route_preview",
    "apply_route_tuning",
    "append_cleaning_operation",
    "SitePackageComplianceResult",
    "compute_site_package_content_sha256",
    "create_site_package",
    "generate_site_package_id",
    "refresh_site_package",
    "validate_site_package",
    "PcdCloud",
    "PcdSchema",
    "read_pcd",
    "write_pcd",
    "DEFAULT_PERCENTILES",
    "summarize_pointcloud",
    "PointCloudProcessingCompliance",
    "PointCloudProcessingResult",
    "load_pointcloud_recipe",
    "process_pointcloud",
    "validate_pointcloud_processing",
    "FREE",
    "OCCUPIED",
    "UNKNOWN",
    "NAVIGATION_DERIVATION_SCHEMA",
    "GroundRelativeNavigationConfig",
    "NavigationMapResult",
    "apply_navigation_overrides",
    "derive_ground_relative_navigation_map",
    "write_navigation_map_derivation",
    "NavigationGridEvidence",
    "load_navigation_grid",
    "NavigationStructureConfig",
    "NavigationStructureResult",
    "RowModel",
    "derive_navigation_structure",
    "AislePairDiagnostic",
    "CorridorRefinementConfig",
    "CorridorRefinementResult",
    "derive_corridor_refinement",
    "VehicleCorridorConfig",
    "VehicleCorridorResult",
    "derive_vehicle_corridor",
    "AISLE_GRAPH_SCHEMA",
    "AisleGraphConfig",
    "AislePrimitive",
    "AgriculturalAisleGraph",
    "aisle_graph_to_dict",
    "derive_agricultural_aisle_graph",
    "write_agricultural_aisle_graph",
    "TURN_ZONE_SCHEMA",
    "TurnZone",
    "TurnZoneConfig",
    "TurnZoneSet",
    "derive_turn_zone_candidates",
    "turn_zones_to_dict",
    "write_turn_zones",
    "CanonicalVehicleProfile",
    "load_canonical_vehicle_profile",
    "vehicle_profile_to_route_binding",
    "COVERAGE_ORDER_SCHEMA",
    "AisleRejection",
    "AisleTraversal",
    "AgriculturalCoverageOrder",
    "ConnectorRequest",
    "CoverageOrderingConfig",
    "coverage_order_to_dict",
    "derive_agricultural_coverage_order",
    "FORWARD_CONNECTOR_SCHEMA",
    "ForwardConnectorConfig",
    "ForwardConnectorPlan",
    "ForwardConnectorResult",
    "ForwardConnectorSample",
    "derive_forward_connector_plan",
    "forward_connector_plan_to_dict",
    "FORWARD_CONNECTOR_ZONE_FIT_SCHEMA",
    "ForwardConnectorZoneFitDiagnostic",
    "ForwardConnectorZoneFitReport",
    "diagnose_forward_connector_zone_fit",
    "forward_connector_zone_fit_to_dict",
    "write_forward_connector_zone_fit_report",
    "FORWARD_CONNECTOR_NAVIGATION_GATE_SCHEMA",
    "ForwardConnectorNavigationGateConfig",
    "ForwardConnectorNavigationPlan",
    "ForwardConnectorNavigationResult",
    "GridPathEvidence",
    "derive_forward_connector_navigation_gate",
    "forward_connector_navigation_gate_to_dict",
    "write_forward_connector_navigation_gate",
    "FORWARD_CONNECTOR_CANDIDATE_AUDIT_SCHEMA",
    "ForwardCandidateAuditItem",
    "ForwardConnectorCandidateAuditConfig",
    "ForwardConnectorCandidateAuditPlan",
    "ForwardConnectorCandidateAuditResult",
    "derive_forward_connector_candidate_audit",
    "forward_connector_candidate_audit_to_dict",
    "write_forward_connector_candidate_audit",
    "TURN_ZONE_REFINEMENT_SCHEMA",
    "TurnZoneExpansionEvidence",
    "TurnZoneRefinementConfig",
    "TurnZoneRefinementPlan",
    "TurnZoneRefinementProposal",
    "derive_turn_zone_refinement_proposal",
    "turn_zone_refinement_to_dict",
    "write_turn_zone_refinement_proposal",
    "REVERSE_FALLBACK_ADMISSION_SCHEMA",
    "ReverseFallbackAdmissionConfig",
    "ReverseFallbackAdmissionItem",
    "ReverseFallbackAdmissionPlan",
    "derive_reverse_fallback_admission",
    "reverse_fallback_admission_to_dict",
    "write_reverse_fallback_admission",
    "load_forward_connector_candidate_audit",
    "load_forward_connector_zone_fit_report",
    "load_agricultural_aisle_graph",
    "load_coverage_connector_requests",
    "load_turn_zones",
    "write_agricultural_coverage_order",
    "write_forward_connector_plan",
    "ASSET_INVALID",
    "ASSET_LOADED",
    "ASSET_MISSING",
    "ROUTE_DEBUG_OVERLAY_SCHEMA",
    "RouteDebugAisleRecord",
    "RouteDebugAssetState",
    "RouteDebugConnectorRecord",
    "RouteDebugCoverageRejection",
    "RouteDebugCoverageTraversal",
    "RouteDebugDataset",
    "RouteDebugForwardCandidateRecord",
    "RouteDebugLaneDiagnosticRecord",
    "RouteDebugMotionSample",
    "RouteDebugNoGoRegion",
    "RouteDebugOccupancySourceRecord",
    "RouteDebugOverlayConfig",
    "RouteDebugVehicleLaneRecord",
    "build_route_debug_overlay",
    "load_route_debug_dataset",
    "write_route_debug_overlay",
    "SITE_BOUNDARY_SCHEMA",
    "SITE_BOUNDARY_SEMANTICS",
    "SiteBoundary",
    "validate_site_boundary",
    "load_site_boundary",
    "write_site_boundary",
    "rasterize_site_boundary",
    "polygon_strictly_inside_site_boundary",
    "TRAVERSABILITY_EVIDENCE_SCHEMA",
    "TraversabilityConfig",
    "TraversabilityEvidence",
    "derive_traversability_evidence",
]