string map_id
string map_version_id
string task_group_id
uint32 expected_revision
string client_request_id
---
uint16 ERROR_NONE=0
uint16 ERROR_INVALID_REQUEST=1
uint16 ERROR_NOT_FOUND=2
uint16 ERROR_REVISION_CONFLICT=3
uint16 ERROR_MAP_NOT_READY=4
uint16 ERROR_INTERNAL=255

bool success
uint16 error_code
string blocker_code
string operator_message
string technical_message
bool duplicate_request
string map_id
string map_version_id
string task_group_id
uint32 archived_revision
string archived_relative_path
