# state=STATE_UNKNOWN disables the state filter.
string map_id
uint8 state
bool include_deleted
---
uint16 ERROR_NONE=0
uint16 ERROR_INVALID_REQUEST=1
uint16 ERROR_INTERNAL=255

bool success
uint16 error_code
MapVersionSummary[] versions
string message
