agt_mission_manager:
  ros__parameters:
    maximum_steps: 100
    maximum_duration_s: 86400.0
    maximum_event_timeout_s: 86400.0
    waypoint_server_wait_timeout_s: 5.0
    localization_status_timeout_s: 10.0
    task_readiness_timeout_s: 3.0
    waypoint_action_name: /agt/navigation/execute_waypoint_task
    execution_backend: sequential
    bt_goal_response_timeout_s: 5.0
    bt_result_timeout_s: 3700.0
    bt_cancel_timeout_s: 2.0
